# Generated by Django 5.0.6 on 2024-05-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('mark', models.TextField()),
                ('car_number', models.CharField(max_length=9)),
                ('manual_transmission', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('tel_number', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=13)),
                ('fillial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=2)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_user_data.auto')),
            ],
        ),
    ]
