# Generated by Django 5.0.6 on 2024-05-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='fillial',
        ),
        migrations.AddField(
            model_name='students',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_user_data.workers'),
        ),
    ]
