# Generated by Django 5.0.6 on 2024-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0003_remove_students_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.TextField(default='Non'),
        ),
    ]
