# Generated by Django 5.0.6 on 2024-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0004_students_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='otchestvo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
