# Generated by Django 5.0.6 on 2024-05-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0005_workers_otchestvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='manual_transmission',
        ),
    ]
