# Generated by Django 5.0.6 on 2024-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0010_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='time',
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(default="0000-00-00"),
        ),
    ]
