# Generated by Django 5.0.6 on 2024-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_user_data', '0011_lessons_time_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='car_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(),
        ),
    ]
